### PR TITLE
Download buttons & README

### PR DESCRIPTION
**Pull request by svalvaro**
Hey @vibalre , I managed to create a function that is able to replicate the code of the image created. It copies the code to the clipboard ( I think this is quite useful). 

I've been testing a few solutions to download the plot as svgs but I couldn't. Feel free to contribute to this PR on Monday when you start.

### CODE REVIEW

**Comment by svalvaro** [comment]
As you can see the feature of copying the code works perfectly :) 
Screenshot 2022-11-04 at 18 55 01
Screenshot 2022-11-04 at 18 55 26

**Comment by svalvaro** [comment]
I was able to fix the README :)

**Comment by vibalre** [comment]
I created a new branch [feat/add-download-buttons](https://github.com/svalvaro/drawCell/tree/feat/add-download-buttons) that rearranged the buttons and added them some `shiny.semantic` classes to make them more consistent with the app's overall look. I also tried the download button, but I cannot make it work too. I thought the most straightforward was to use [`shinyscreenshot`](https://github.com/daattali/shinyscreenshot). Unfortunately, it cannot capture `svg` images. I tested, and `shinyscreenshot` can capture all elements of the app except for the cell.

How where you able to fix `README`. I am trying to knit locally, but I am only getting blank images in my rendered `README`. I think I am missing some  package or have a bad setting.

**Comment by vibalre** [comment]
I added a couple more changes to [feat/add-download-buttons](https://github.com/svalvaro/drawCell/tree/feat/add-download-buttons). I added a `toast` when the user clicks copy the code to clipboard to indicate that the code is ready for pasting. Plus more rearrangement of the elements to make their flow better when resizing the window. I gave the cell a minimum width of `35rem`, but that includes the empty space on the right side of the cell. This makes it look quite big in RStudio's viewer pane, but still quite small in the browser. I also created a new funciton `find_unique_subcellular_location()`, based on your fix for the animal cell because I also need to use this in the clear colors button. In my tests, when I cleared colors, the animal cell reverts to the default animal cell even though I have egg cell, for example, selected. My only concern with this fix is that the unique subcellular location for the selected cell will always be on display. With how SwissBioPic API works, I am not sure if we have a better way to resolve this.

**Comment by svalvaro** [comment]
> I created a new branch [feat/add-download-buttons](https://github.com/svalvaro/drawCell/tree/feat/add-download-buttons) that rearranged the buttons and added them some `shiny.semantic` classes to make them more consistent with the app's overall look. I also tried the download button, but I cannot make it work too. I thought the most straightforward was to use [`shinyscreenshot`](https://github.com/daattali/shinyscreenshot). Unfortunately, it cannot capture `svg` images. I tested, and `shinyscreenshot` can capture all elements of the app except for the cell.
> 
> How where you able to fix `README`. I am trying to knit locally, but I am only getting blank images in my rendered `README`. I think I am missing some package or have a bad setting.




Great, I think the positioning of the buttons and formatting looks neat.
I was trying to avoid a solution that takes a screenshot 🤔 

The README knits fine for me, and you can see that the  [README](https://github.com/svalvaro/drawCell/tree/download_buttons#readme) from this branch is the newer version with the pictures. What error are you getting?

**Comment by svalvaro** [comment]
> I added a couple more changes to [feat/add-download-buttons](https://github.com/svalvaro/drawCell/tree/feat/add-download-buttons). I added a `toast` when the user clicks copy the code to clipboard to indicate that the code is ready for pasting. Plus more rearrangement of the elements to make their flow better when resizing the window. I gave the cell a minimum width of `35rem`, but that includes the empty space on the right side of the cell. This makes it look quite big in RStudio's viewer pane, but still quite small in the browser. I also created a new funciton `find_unique_subcellular_location()`, based on your fix for the animal cell because I also need to use this in the clear colors button. In my tests, when I cleared colors, the animal cell reverts to the default animal cell even though I have egg cell, for example, selected. My only concern with this fix is that the unique subcellular location for the selected cell will always be on display. With how SwissBioPic API works, I am not sure if we have a better way to resolve this.

Nice! I like that toast, I didn't know about that. It's always about giving feedback to the user.

**Comment by svalvaro** [comment]
Closing this PR since the content was merged in #18

**Pull request closed without merging**
